spring.sql.init.mode: always
# spring.sql.init.platform: postgres
spring.datasource.url: jdbc:sqlserver://sql-autoscale-8650.database.windows.net:1433;database=sqldb-autoscale-8650;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username: dbadmin@sql-autoscale-8650
spring.datasource.password: P4ssw0rd#777

spring.jpa.hibernate.ddl-auto: update
# spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# azure.eventhub.connectionString: ${AZURE_EVENTHUB_CONNECTION_STRING}
# azure.eventhub.name: ${AZURE_EVENTHUB_NAME}